# Generated by Django 5.0.6 on 2025-08-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_add_criterios_profesionales_y_sii'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='bank_account_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('connected', 'Conectada'), ('failed', 'Falló'), ('disconnected', 'Desconectada')], default='pending', help_text='CAMPO RESERVADO - No usar hasta activar funcionalidad bancaria', max_length=50),
        ),
    ]
