# Generated by Django 5.0.6 on 2025-08-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_add_criterios_profesionales_y_sii'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeDiarioCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('html_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'alerts_informediariocache',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha'], name='alerts_info_fecha_7466e8_idx')],
            },
        ),
    ]