# Generated by Django 5.0.6 on 2025-08-18 22:02

import alerts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_informediariocache'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='bank_account_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('connected', 'Conectada'), ('failed', 'Falló'), ('disconnected', 'Desconectada')], default='pending', help_text='CAMPO RESERVADO - No usar hasta activar funcionalidad bancaria', max_length=50),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='rut',
            field=models.CharField(blank=True, help_text='RUT en formato NNNNNNNN-DV (sin puntos, DV mayúscula)', max_length=11, null=True, unique=True, validators=[alerts.validators.validar_rut_estricto]),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='tipo',
            field=models.CharField(choices=[('empresa', 'Empresa'), ('independiente', 'Independiente')], default='independiente', help_text='Tipo de organización: Empresa (con RUT) o Independiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='dominio',
            field=models.CharField(blank=True, help_text='Campo legacy - no se usa para agrupar', max_length=80, null=True),
        ),
    ]
