# Generated by Django 5.0.6 on 2025-08-26 02:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_merge_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatario',
            name='es_pagado',
            field=models.BooleanField(default=False, help_text='Indica si el cliente tiene una suscripción pagada activa'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='fecha_fin_trial',
            field=models.DateTimeField(blank=True, help_text='Fecha de fin del período de prueba (se calcula automáticamente)', null=True),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='fecha_inicio_trial',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de inicio del período de prueba'),
        ),
    ]
