# Generated by Django 5.0.6 on 2025-09-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0011_add_subscription_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente - Requiere Tarjeta'), ('trial', 'Período de Prueba'), ('active', 'Activa'), ('past_due', 'Pago Pendiente'), ('canceled', 'Cancelada'), ('expired', 'Expirada')], default='trial', max_length=20),
        ),
    ]
